spring:
  datasource:
    username: postgres
    password: ESD2023
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marjanepromotion
  jpa:
    hibernate:
      ddl-auto: create
